[package]
name = "alou_code_runtime"
version = "0.1.0"
edition = "2021"
license = "MIT"
publish = false

[dependencies]
sha2 = "0.10"
glob = "0.3"
alou_code_plugins = { path = "../plugins" }
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
telemetry = { package = "alou_code_telemetry", path = "../telemetry" }
tokio = { version = "1", features = ["io-std", "io-util", "macros", "process", "rt", "rt-multi-thread", "time"] }
walkdir = "2"
polymarket-client-sdk = { version = "0.4.4", features = ["clob", "gamma"] }
reqwest = { version = "0.12", default-features = false, features = ["blocking", "rustls-tls", "json"] }
num-bigint = "0.4"
dotenv = "0.15"