/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace DIAPAgentNetwork {
  export type AgentStruct = {
    didDocument: string;
    publicKey: string;
    stakedAmount: BigNumberish;
    totalEarnings: BigNumberish;
    reputation: BigNumberish;
    registrationTime: BigNumberish;
    lastActivity: BigNumberish;
    totalServices: BigNumberish;
    isActive: boolean;
    isVerified: boolean;
    aaAccount: AddressLike;
    isAAAccount: boolean;
  };

  export type AgentStructOutput = [
    didDocument: string,
    publicKey: string,
    stakedAmount: bigint,
    totalEarnings: bigint,
    reputation: bigint,
    registrationTime: bigint,
    lastActivity: bigint,
    totalServices: bigint,
    isActive: boolean,
    isVerified: boolean,
    aaAccount: string,
    isAAAccount: boolean
  ] & {
    didDocument: string;
    publicKey: string;
    stakedAmount: bigint;
    totalEarnings: bigint;
    reputation: bigint;
    registrationTime: bigint;
    lastActivity: bigint;
    totalServices: bigint;
    isActive: boolean;
    isVerified: boolean;
    aaAccount: string;
    isAAAccount: boolean;
  };

  export type MessageStruct = {
    fromAgent: AddressLike;
    toAgent: AddressLike;
    messageCID: string;
    timestamp: BigNumberish;
    isVerified: boolean;
    fee: BigNumberish;
  };

  export type MessageStructOutput = [
    fromAgent: string,
    toAgent: string,
    messageCID: string,
    timestamp: bigint,
    isVerified: boolean,
    fee: bigint
  ] & {
    fromAgent: string;
    toAgent: string;
    messageCID: string;
    timestamp: bigint;
    isVerified: boolean;
    fee: bigint;
  };

  export type ServiceStruct = {
    provider: AddressLike;
    consumer: AddressLike;
    serviceType: string;
    price: BigNumberish;
    timestamp: BigNumberish;
    isCompleted: boolean;
    resultCID: string;
  };

  export type ServiceStructOutput = [
    provider: string,
    consumer: string,
    serviceType: string,
    price: bigint,
    timestamp: bigint,
    isCompleted: boolean,
    resultCID: string
  ] & {
    provider: string;
    consumer: string;
    serviceType: string;
    price: bigint;
    timestamp: bigint;
    isCompleted: boolean;
    resultCID: string;
  };
}

export interface DIAPAgentNetworkInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BATCH_SIZE"
      | "accountFactory"
      | "accumulatedFees"
      | "agentIndex"
      | "agentList"
      | "agentMetadataCID"
      | "agents"
      | "completeService"
      | "createService"
      | "didToAgent"
      | "distributeRewards"
      | "getAgent"
      | "getAgentAAAccount"
      | "getAgentIdentifierType"
      | "getAgentTokenBalance"
      | "getMessage"
      | "getNetworkStats"
      | "getService"
      | "initialize"
      | "isAgentUsingAA"
      | "isValidCaller"
      | "lastProcessedIndex"
      | "lastRewardTime"
      | "lockPeriod"
      | "messageFee"
      | "messages"
      | "minStakeAmount"
      | "owner"
      | "pause"
      | "paused"
      | "pendingRewards"
      | "processRewardBatch"
      | "proxiableUUID"
      | "registerAgent"
      | "registerAgentWithAA"
      | "registrationFee"
      | "renounceOwnership"
      | "reputationThreshold"
      | "rewardRate"
      | "sendMessage"
      | "serviceFeeRate"
      | "serviceMetadataCID"
      | "services"
      | "setAccountFactory"
      | "setAgentMetadataCID"
      | "setMessageFee"
      | "setMinStakeAmount"
      | "setRegistrationFee"
      | "setRewardRate"
      | "setServiceFeeRate"
      | "setServiceMetadataCID"
      | "setTreasuryAddress"
      | "setVerificationContract"
      | "token"
      | "totalAgents"
      | "totalMessages"
      | "totalRewards"
      | "totalServices"
      | "totalStaked"
      | "totalVolume"
      | "transferOwnership"
      | "treasuryAddress"
      | "unpause"
      | "unstakeAgent"
      | "updateReputation"
      | "upgradeTo"
      | "upgradeToAndCall"
      | "verification"
      | "verifyAgent"
      | "withdrawFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AAAccountCreated"
      | "AccountFactoryUpdated"
      | "AdminChanged"
      | "AgentRegistered"
      | "AgentRegisteredWithIPNS"
      | "AgentUnstaked"
      | "AgentVerified"
      | "BeaconUpgraded"
      | "FeesWithdrawn"
      | "Initialized"
      | "MessageSent"
      | "OwnershipTransferred"
      | "Paused"
      | "ReputationUpdated"
      | "RewardsDistributed"
      | "ServiceCompleted"
      | "ServiceCreated"
      | "TreasuryAddressUpdated"
      | "Unpaused"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BATCH_SIZE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "accountFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "accumulatedFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agentIndex",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "agentList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "agentMetadataCID",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "agents", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "completeService",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createService",
    values: [AddressLike, string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "didToAgent", values: [string]): string;
  encodeFunctionData(
    functionFragment: "distributeRewards",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentAAAccount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentIdentifierType",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentTokenBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMessage",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNetworkStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getService",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAgentUsingAA",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidCaller",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastProcessedIndex",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastRewardTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lockPeriod",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "messageFee",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "messages", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "minStakeAmount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingRewards",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "processRewardBatch",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAgentWithAA",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registrationFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reputationThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rewardRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sendMessage",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "serviceFeeRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "serviceMetadataCID",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "services",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAccountFactory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAgentMetadataCID",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setMessageFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinStakeAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setRegistrationFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setRewardRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setServiceFeeRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setServiceMetadataCID",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasuryAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setVerificationContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalAgents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalMessages",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalRewards",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalServices",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalStaked",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalVolume",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "treasuryAddress",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "unstakeAgent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateReputation",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeTo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verification",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verifyAgent",
    values: [AddressLike, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFees",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "BATCH_SIZE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "accountFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "accumulatedFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "agentIndex", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "agentList", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "agentMetadataCID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "agents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "completeService",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createService",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "didToAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "distributeRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAgentAAAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentIdentifierType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentTokenBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMessage", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getNetworkStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getService", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isAgentUsingAA",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidCaller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastProcessedIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastRewardTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lockPeriod", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "messageFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "messages", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "minStakeAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processRewardBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAgentWithAA",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registrationFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reputationThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rewardRate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sendMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "serviceFeeRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "serviceMetadataCID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "services", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAccountFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAgentMetadataCID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMessageFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinStakeAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRegistrationFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRewardRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setServiceFeeRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setServiceMetadataCID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasuryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVerificationContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalMessages",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalServices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalStaked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalVolume",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "treasuryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unstakeAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "upgradeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFees",
    data: BytesLike
  ): Result;
}

export namespace AAAccountCreatedEvent {
  export type InputTuple = [
    agent: AddressLike,
    aaAccount: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    agent: string,
    aaAccount: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    agent: string;
    aaAccount: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AccountFactoryUpdatedEvent {
  export type InputTuple = [oldFactory: AddressLike, newFactory: AddressLike];
  export type OutputTuple = [oldFactory: string, newFactory: string];
  export interface OutputObject {
    oldFactory: string;
    newFactory: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AdminChangedEvent {
  export type InputTuple = [previousAdmin: AddressLike, newAdmin: AddressLike];
  export type OutputTuple = [previousAdmin: string, newAdmin: string];
  export interface OutputObject {
    previousAdmin: string;
    newAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [
    agent: AddressLike,
    didDocument: string,
    stakedAmount: BigNumberish
  ];
  export type OutputTuple = [
    agent: string,
    didDocument: string,
    stakedAmount: bigint
  ];
  export interface OutputObject {
    agent: string;
    didDocument: string;
    stakedAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentRegisteredWithIPNSEvent {
  export type InputTuple = [
    agent: AddressLike,
    ipnsName: string,
    stakedAmount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    agent: string,
    ipnsName: string,
    stakedAmount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    agent: string;
    ipnsName: string;
    stakedAmount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentUnstakedEvent {
  export type InputTuple = [agent: AddressLike, stakedAmount: BigNumberish];
  export type OutputTuple = [agent: string, stakedAmount: bigint];
  export interface OutputObject {
    agent: string;
    stakedAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentVerifiedEvent {
  export type InputTuple = [agent: AddressLike, isVerified: boolean];
  export type OutputTuple = [agent: string, isVerified: boolean];
  export interface OutputObject {
    agent: string;
    isVerified: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BeaconUpgradedEvent {
  export type InputTuple = [beacon: AddressLike];
  export type OutputTuple = [beacon: string];
  export interface OutputObject {
    beacon: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeesWithdrawnEvent {
  export type InputTuple = [
    to: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [to: string, amount: bigint, timestamp: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MessageSentEvent {
  export type InputTuple = [
    messageId: BytesLike,
    from: AddressLike,
    to: AddressLike,
    fee: BigNumberish
  ];
  export type OutputTuple = [
    messageId: string,
    from: string,
    to: string,
    fee: bigint
  ];
  export interface OutputObject {
    messageId: string;
    from: string;
    to: string;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReputationUpdatedEvent {
  export type InputTuple = [
    agent: AddressLike,
    oldReputation: BigNumberish,
    newReputation: BigNumberish
  ];
  export type OutputTuple = [
    agent: string,
    oldReputation: bigint,
    newReputation: bigint
  ];
  export interface OutputObject {
    agent: string;
    oldReputation: bigint;
    newReputation: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsDistributedEvent {
  export type InputTuple = [totalAmount: BigNumberish, timestamp: BigNumberish];
  export type OutputTuple = [totalAmount: bigint, timestamp: bigint];
  export interface OutputObject {
    totalAmount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ServiceCompletedEvent {
  export type InputTuple = [
    serviceId: BigNumberish,
    resultCID: string,
    reward: BigNumberish
  ];
  export type OutputTuple = [
    serviceId: bigint,
    resultCID: string,
    reward: bigint
  ];
  export interface OutputObject {
    serviceId: bigint;
    resultCID: string;
    reward: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ServiceCreatedEvent {
  export type InputTuple = [
    serviceId: BigNumberish,
    provider: AddressLike,
    consumer: AddressLike,
    price: BigNumberish
  ];
  export type OutputTuple = [
    serviceId: bigint,
    provider: string,
    consumer: string,
    price: bigint
  ];
  export interface OutputObject {
    serviceId: bigint;
    provider: string;
    consumer: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryAddressUpdatedEvent {
  export type InputTuple = [oldAddress: AddressLike, newAddress: AddressLike];
  export type OutputTuple = [oldAddress: string, newAddress: string];
  export interface OutputObject {
    oldAddress: string;
    newAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DIAPAgentNetwork extends BaseContract {
  connect(runner?: ContractRunner | null): DIAPAgentNetwork;
  waitForDeployment(): Promise<this>;

  interface: DIAPAgentNetworkInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BATCH_SIZE: TypedContractMethod<[], [bigint], "view">;

  accountFactory: TypedContractMethod<[], [string], "view">;

  accumulatedFees: TypedContractMethod<[], [bigint], "view">;

  agentIndex: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  agentList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  agentMetadataCID: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  agents: TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        string,
        boolean
      ] & {
        didDocument: string;
        publicKey: string;
        stakedAmount: bigint;
        totalEarnings: bigint;
        reputation: bigint;
        registrationTime: bigint;
        lastActivity: bigint;
        totalServices: bigint;
        isActive: boolean;
        isVerified: boolean;
        aaAccount: string;
        isAAAccount: boolean;
      }
    ],
    "view"
  >;

  completeService: TypedContractMethod<
    [serviceId: BigNumberish, resultCID: string],
    [void],
    "nonpayable"
  >;

  createService: TypedContractMethod<
    [consumer: AddressLike, serviceType: string, price: BigNumberish],
    [void],
    "nonpayable"
  >;

  didToAgent: TypedContractMethod<[arg0: string], [string], "view">;

  distributeRewards: TypedContractMethod<[], [void], "nonpayable">;

  getAgent: TypedContractMethod<
    [agent: AddressLike],
    [DIAPAgentNetwork.AgentStructOutput],
    "view"
  >;

  getAgentAAAccount: TypedContractMethod<
    [agent: AddressLike],
    [string],
    "view"
  >;

  getAgentIdentifierType: TypedContractMethod<
    [agent: AddressLike],
    [bigint],
    "view"
  >;

  getAgentTokenBalance: TypedContractMethod<
    [agent: AddressLike],
    [bigint],
    "view"
  >;

  getMessage: TypedContractMethod<
    [messageId: BytesLike],
    [DIAPAgentNetwork.MessageStructOutput],
    "view"
  >;

  getNetworkStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        _totalAgents: bigint;
        _totalMessages: bigint;
        _totalServices: bigint;
        _totalVolume: bigint;
        _totalRewards: bigint;
      }
    ],
    "view"
  >;

  getService: TypedContractMethod<
    [serviceId: BigNumberish],
    [DIAPAgentNetwork.ServiceStructOutput],
    "view"
  >;

  initialize: TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;

  isAgentUsingAA: TypedContractMethod<[agent: AddressLike], [boolean], "view">;

  isValidCaller: TypedContractMethod<
    [agent: AddressLike, caller: AddressLike],
    [boolean],
    "view"
  >;

  lastProcessedIndex: TypedContractMethod<[], [bigint], "view">;

  lastRewardTime: TypedContractMethod<[], [bigint], "view">;

  lockPeriod: TypedContractMethod<[], [bigint], "view">;

  messageFee: TypedContractMethod<[], [bigint], "view">;

  messages: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, boolean, bigint] & {
        fromAgent: string;
        toAgent: string;
        messageCID: string;
        timestamp: bigint;
        isVerified: boolean;
        fee: bigint;
      }
    ],
    "view"
  >;

  minStakeAmount: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pendingRewards: TypedContractMethod<[], [bigint], "view">;

  processRewardBatch: TypedContractMethod<[], [boolean], "nonpayable">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  registerAgent: TypedContractMethod<
    [didDocument: string, publicKey: string, stakedAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  registerAgentWithAA: TypedContractMethod<
    [
      didDocument: string,
      publicKey: string,
      stakedAmount: BigNumberish,
      salt: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  registrationFee: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reputationThreshold: TypedContractMethod<[], [bigint], "view">;

  rewardRate: TypedContractMethod<[], [bigint], "view">;

  sendMessage: TypedContractMethod<
    [toAgent: AddressLike, messageCID: string],
    [void],
    "nonpayable"
  >;

  serviceFeeRate: TypedContractMethod<[], [bigint], "view">;

  serviceMetadataCID: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  services: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, bigint, boolean, string] & {
        provider: string;
        consumer: string;
        serviceType: string;
        price: bigint;
        timestamp: bigint;
        isCompleted: boolean;
        resultCID: string;
      }
    ],
    "view"
  >;

  setAccountFactory: TypedContractMethod<
    [_factory: AddressLike],
    [void],
    "nonpayable"
  >;

  setAgentMetadataCID: TypedContractMethod<
    [agent: AddressLike, metadataCID: string],
    [void],
    "nonpayable"
  >;

  setMessageFee: TypedContractMethod<
    [_fee: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMinStakeAmount: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setRegistrationFee: TypedContractMethod<
    [_fee: BigNumberish],
    [void],
    "nonpayable"
  >;

  setRewardRate: TypedContractMethod<
    [_rate: BigNumberish],
    [void],
    "nonpayable"
  >;

  setServiceFeeRate: TypedContractMethod<
    [_rate: BigNumberish],
    [void],
    "nonpayable"
  >;

  setServiceMetadataCID: TypedContractMethod<
    [serviceId: BigNumberish, metadataCID: string],
    [void],
    "nonpayable"
  >;

  setTreasuryAddress: TypedContractMethod<
    [_treasury: AddressLike],
    [void],
    "nonpayable"
  >;

  setVerificationContract: TypedContractMethod<
    [_verification: AddressLike],
    [void],
    "nonpayable"
  >;

  token: TypedContractMethod<[], [string], "view">;

  totalAgents: TypedContractMethod<[], [bigint], "view">;

  totalMessages: TypedContractMethod<[], [bigint], "view">;

  totalRewards: TypedContractMethod<[], [bigint], "view">;

  totalServices: TypedContractMethod<[], [bigint], "view">;

  totalStaked: TypedContractMethod<[], [bigint], "view">;

  totalVolume: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasuryAddress: TypedContractMethod<[], [string], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  unstakeAgent: TypedContractMethod<[], [void], "nonpayable">;

  updateReputation: TypedContractMethod<
    [agent: AddressLike, reputationChange: BigNumberish],
    [void],
    "nonpayable"
  >;

  upgradeTo: TypedContractMethod<
    [newImplementation: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  verification: TypedContractMethod<[], [string], "view">;

  verifyAgent: TypedContractMethod<
    [agent: AddressLike, proof: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  withdrawFees: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BATCH_SIZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "accountFactory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "accumulatedFees"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "agentIndex"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "agentList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "agentMetadataCID"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "agents"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        string,
        boolean
      ] & {
        didDocument: string;
        publicKey: string;
        stakedAmount: bigint;
        totalEarnings: bigint;
        reputation: bigint;
        registrationTime: bigint;
        lastActivity: bigint;
        totalServices: bigint;
        isActive: boolean;
        isVerified: boolean;
        aaAccount: string;
        isAAAccount: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "completeService"
  ): TypedContractMethod<
    [serviceId: BigNumberish, resultCID: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createService"
  ): TypedContractMethod<
    [consumer: AddressLike, serviceType: string, price: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "didToAgent"
  ): TypedContractMethod<[arg0: string], [string], "view">;
  getFunction(
    nameOrSignature: "distributeRewards"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAgent"
  ): TypedContractMethod<
    [agent: AddressLike],
    [DIAPAgentNetwork.AgentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgentAAAccount"
  ): TypedContractMethod<[agent: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getAgentIdentifierType"
  ): TypedContractMethod<[agent: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAgentTokenBalance"
  ): TypedContractMethod<[agent: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMessage"
  ): TypedContractMethod<
    [messageId: BytesLike],
    [DIAPAgentNetwork.MessageStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getNetworkStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        _totalAgents: bigint;
        _totalMessages: bigint;
        _totalServices: bigint;
        _totalVolume: bigint;
        _totalRewards: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getService"
  ): TypedContractMethod<
    [serviceId: BigNumberish],
    [DIAPAgentNetwork.ServiceStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isAgentUsingAA"
  ): TypedContractMethod<[agent: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isValidCaller"
  ): TypedContractMethod<
    [agent: AddressLike, caller: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "lastProcessedIndex"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastRewardTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lockPeriod"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "messageFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "messages"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, boolean, bigint] & {
        fromAgent: string;
        toAgent: string;
        messageCID: string;
        timestamp: bigint;
        isVerified: boolean;
        fee: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "minStakeAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingRewards"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "processRewardBatch"
  ): TypedContractMethod<[], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<
    [didDocument: string, publicKey: string, stakedAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerAgentWithAA"
  ): TypedContractMethod<
    [
      didDocument: string,
      publicKey: string,
      stakedAmount: BigNumberish,
      salt: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registrationFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reputationThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "rewardRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "sendMessage"
  ): TypedContractMethod<
    [toAgent: AddressLike, messageCID: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "serviceFeeRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "serviceMetadataCID"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "services"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, bigint, boolean, string] & {
        provider: string;
        consumer: string;
        serviceType: string;
        price: bigint;
        timestamp: bigint;
        isCompleted: boolean;
        resultCID: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setAccountFactory"
  ): TypedContractMethod<[_factory: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAgentMetadataCID"
  ): TypedContractMethod<
    [agent: AddressLike, metadataCID: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMessageFee"
  ): TypedContractMethod<[_fee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMinStakeAmount"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRegistrationFee"
  ): TypedContractMethod<[_fee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRewardRate"
  ): TypedContractMethod<[_rate: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setServiceFeeRate"
  ): TypedContractMethod<[_rate: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setServiceMetadataCID"
  ): TypedContractMethod<
    [serviceId: BigNumberish, metadataCID: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTreasuryAddress"
  ): TypedContractMethod<[_treasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVerificationContract"
  ): TypedContractMethod<[_verification: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalAgents"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalMessages"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalRewards"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalServices"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalStaked"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalVolume"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasuryAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unstakeAgent"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateReputation"
  ): TypedContractMethod<
    [agent: AddressLike, reputationChange: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeTo"
  ): TypedContractMethod<
    [newImplementation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "verification"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifyAgent"
  ): TypedContractMethod<
    [agent: AddressLike, proof: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawFees"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "AAAccountCreated"
  ): TypedContractEvent<
    AAAccountCreatedEvent.InputTuple,
    AAAccountCreatedEvent.OutputTuple,
    AAAccountCreatedEvent.OutputObject
  >;
  getEvent(
    key: "AccountFactoryUpdated"
  ): TypedContractEvent<
    AccountFactoryUpdatedEvent.InputTuple,
    AccountFactoryUpdatedEvent.OutputTuple,
    AccountFactoryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "AdminChanged"
  ): TypedContractEvent<
    AdminChangedEvent.InputTuple,
    AdminChangedEvent.OutputTuple,
    AdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "AgentRegisteredWithIPNS"
  ): TypedContractEvent<
    AgentRegisteredWithIPNSEvent.InputTuple,
    AgentRegisteredWithIPNSEvent.OutputTuple,
    AgentRegisteredWithIPNSEvent.OutputObject
  >;
  getEvent(
    key: "AgentUnstaked"
  ): TypedContractEvent<
    AgentUnstakedEvent.InputTuple,
    AgentUnstakedEvent.OutputTuple,
    AgentUnstakedEvent.OutputObject
  >;
  getEvent(
    key: "AgentVerified"
  ): TypedContractEvent<
    AgentVerifiedEvent.InputTuple,
    AgentVerifiedEvent.OutputTuple,
    AgentVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "BeaconUpgraded"
  ): TypedContractEvent<
    BeaconUpgradedEvent.InputTuple,
    BeaconUpgradedEvent.OutputTuple,
    BeaconUpgradedEvent.OutputObject
  >;
  getEvent(
    key: "FeesWithdrawn"
  ): TypedContractEvent<
    FeesWithdrawnEvent.InputTuple,
    FeesWithdrawnEvent.OutputTuple,
    FeesWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "MessageSent"
  ): TypedContractEvent<
    MessageSentEvent.InputTuple,
    MessageSentEvent.OutputTuple,
    MessageSentEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "ReputationUpdated"
  ): TypedContractEvent<
    ReputationUpdatedEvent.InputTuple,
    ReputationUpdatedEvent.OutputTuple,
    ReputationUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RewardsDistributed"
  ): TypedContractEvent<
    RewardsDistributedEvent.InputTuple,
    RewardsDistributedEvent.OutputTuple,
    RewardsDistributedEvent.OutputObject
  >;
  getEvent(
    key: "ServiceCompleted"
  ): TypedContractEvent<
    ServiceCompletedEvent.InputTuple,
    ServiceCompletedEvent.OutputTuple,
    ServiceCompletedEvent.OutputObject
  >;
  getEvent(
    key: "ServiceCreated"
  ): TypedContractEvent<
    ServiceCreatedEvent.InputTuple,
    ServiceCreatedEvent.OutputTuple,
    ServiceCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryAddressUpdated"
  ): TypedContractEvent<
    TreasuryAddressUpdatedEvent.InputTuple,
    TreasuryAddressUpdatedEvent.OutputTuple,
    TreasuryAddressUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "AAAccountCreated(address,address,uint256)": TypedContractEvent<
      AAAccountCreatedEvent.InputTuple,
      AAAccountCreatedEvent.OutputTuple,
      AAAccountCreatedEvent.OutputObject
    >;
    AAAccountCreated: TypedContractEvent<
      AAAccountCreatedEvent.InputTuple,
      AAAccountCreatedEvent.OutputTuple,
      AAAccountCreatedEvent.OutputObject
    >;

    "AccountFactoryUpdated(address,address)": TypedContractEvent<
      AccountFactoryUpdatedEvent.InputTuple,
      AccountFactoryUpdatedEvent.OutputTuple,
      AccountFactoryUpdatedEvent.OutputObject
    >;
    AccountFactoryUpdated: TypedContractEvent<
      AccountFactoryUpdatedEvent.InputTuple,
      AccountFactoryUpdatedEvent.OutputTuple,
      AccountFactoryUpdatedEvent.OutputObject
    >;

    "AdminChanged(address,address)": TypedContractEvent<
      AdminChangedEvent.InputTuple,
      AdminChangedEvent.OutputTuple,
      AdminChangedEvent.OutputObject
    >;
    AdminChanged: TypedContractEvent<
      AdminChangedEvent.InputTuple,
      AdminChangedEvent.OutputTuple,
      AdminChangedEvent.OutputObject
    >;

    "AgentRegistered(address,string,uint256)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "AgentRegisteredWithIPNS(address,string,uint256,uint256)": TypedContractEvent<
      AgentRegisteredWithIPNSEvent.InputTuple,
      AgentRegisteredWithIPNSEvent.OutputTuple,
      AgentRegisteredWithIPNSEvent.OutputObject
    >;
    AgentRegisteredWithIPNS: TypedContractEvent<
      AgentRegisteredWithIPNSEvent.InputTuple,
      AgentRegisteredWithIPNSEvent.OutputTuple,
      AgentRegisteredWithIPNSEvent.OutputObject
    >;

    "AgentUnstaked(address,uint256)": TypedContractEvent<
      AgentUnstakedEvent.InputTuple,
      AgentUnstakedEvent.OutputTuple,
      AgentUnstakedEvent.OutputObject
    >;
    AgentUnstaked: TypedContractEvent<
      AgentUnstakedEvent.InputTuple,
      AgentUnstakedEvent.OutputTuple,
      AgentUnstakedEvent.OutputObject
    >;

    "AgentVerified(address,bool)": TypedContractEvent<
      AgentVerifiedEvent.InputTuple,
      AgentVerifiedEvent.OutputTuple,
      AgentVerifiedEvent.OutputObject
    >;
    AgentVerified: TypedContractEvent<
      AgentVerifiedEvent.InputTuple,
      AgentVerifiedEvent.OutputTuple,
      AgentVerifiedEvent.OutputObject
    >;

    "BeaconUpgraded(address)": TypedContractEvent<
      BeaconUpgradedEvent.InputTuple,
      BeaconUpgradedEvent.OutputTuple,
      BeaconUpgradedEvent.OutputObject
    >;
    BeaconUpgraded: TypedContractEvent<
      BeaconUpgradedEvent.InputTuple,
      BeaconUpgradedEvent.OutputTuple,
      BeaconUpgradedEvent.OutputObject
    >;

    "FeesWithdrawn(address,uint256,uint256)": TypedContractEvent<
      FeesWithdrawnEvent.InputTuple,
      FeesWithdrawnEvent.OutputTuple,
      FeesWithdrawnEvent.OutputObject
    >;
    FeesWithdrawn: TypedContractEvent<
      FeesWithdrawnEvent.InputTuple,
      FeesWithdrawnEvent.OutputTuple,
      FeesWithdrawnEvent.OutputObject
    >;

    "Initialized(uint8)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "MessageSent(bytes32,address,address,uint256)": TypedContractEvent<
      MessageSentEvent.InputTuple,
      MessageSentEvent.OutputTuple,
      MessageSentEvent.OutputObject
    >;
    MessageSent: TypedContractEvent<
      MessageSentEvent.InputTuple,
      MessageSentEvent.OutputTuple,
      MessageSentEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "ReputationUpdated(address,uint256,uint256)": TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;
    ReputationUpdated: TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;

    "RewardsDistributed(uint256,uint256)": TypedContractEvent<
      RewardsDistributedEvent.InputTuple,
      RewardsDistributedEvent.OutputTuple,
      RewardsDistributedEvent.OutputObject
    >;
    RewardsDistributed: TypedContractEvent<
      RewardsDistributedEvent.InputTuple,
      RewardsDistributedEvent.OutputTuple,
      RewardsDistributedEvent.OutputObject
    >;

    "ServiceCompleted(uint256,string,uint256)": TypedContractEvent<
      ServiceCompletedEvent.InputTuple,
      ServiceCompletedEvent.OutputTuple,
      ServiceCompletedEvent.OutputObject
    >;
    ServiceCompleted: TypedContractEvent<
      ServiceCompletedEvent.InputTuple,
      ServiceCompletedEvent.OutputTuple,
      ServiceCompletedEvent.OutputObject
    >;

    "ServiceCreated(uint256,address,address,uint256)": TypedContractEvent<
      ServiceCreatedEvent.InputTuple,
      ServiceCreatedEvent.OutputTuple,
      ServiceCreatedEvent.OutputObject
    >;
    ServiceCreated: TypedContractEvent<
      ServiceCreatedEvent.InputTuple,
      ServiceCreatedEvent.OutputTuple,
      ServiceCreatedEvent.OutputObject
    >;

    "TreasuryAddressUpdated(address,address)": TypedContractEvent<
      TreasuryAddressUpdatedEvent.InputTuple,
      TreasuryAddressUpdatedEvent.OutputTuple,
      TreasuryAddressUpdatedEvent.OutputObject
    >;
    TreasuryAddressUpdated: TypedContractEvent<
      TreasuryAddressUpdatedEvent.InputTuple,
      TreasuryAddressUpdatedEvent.OutputTuple,
      TreasuryAddressUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
