/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IEntryPoint {
  export type UserOperationStruct = {
    sender: AddressLike;
    nonce: BigNumberish;
    initCode: BytesLike;
    callData: BytesLike;
    callGasLimit: BigNumberish;
    verificationGasLimit: BigNumberish;
    preVerificationGas: BigNumberish;
    maxFeePerGas: BigNumberish;
    maxPriorityFeePerGas: BigNumberish;
    paymasterAndData: BytesLike;
    signature: BytesLike;
  };

  export type UserOperationStructOutput = [
    sender: string,
    nonce: bigint,
    initCode: string,
    callData: string,
    callGasLimit: bigint,
    verificationGasLimit: bigint,
    preVerificationGas: bigint,
    maxFeePerGas: bigint,
    maxPriorityFeePerGas: bigint,
    paymasterAndData: string,
    signature: string
  ] & {
    sender: string;
    nonce: bigint;
    initCode: string;
    callData: string;
    callGasLimit: bigint;
    verificationGasLimit: bigint;
    preVerificationGas: bigint;
    maxFeePerGas: bigint;
    maxPriorityFeePerGas: bigint;
    paymasterAndData: string;
    signature: string;
  };
}

export interface DIAPPaymasterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ENTRY_POINT"
      | "accountWhitelist"
      | "addAccountToWhitelist"
      | "addDeposit"
      | "addTargetToWhitelist"
      | "batchAddAccountToWhitelist"
      | "batchAddTargetToWhitelist"
      | "batchSetGasQuota"
      | "defaultDailyQuota"
      | "gasQuotas"
      | "getDeposit"
      | "getGasQuotaInfo"
      | "getStats"
      | "globalDailyLimit"
      | "globalLastResetTime"
      | "globalUsedToday"
      | "isAccountWhitelisted"
      | "isTargetWhitelisted"
      | "owner"
      | "postOp"
      | "removeAccountFromWhitelist"
      | "removeTargetFromWhitelist"
      | "renounceOwnership"
      | "requireWhitelist"
      | "setDefaultDailyQuota"
      | "setGasQuota"
      | "setGlobalDailyLimit"
      | "setRequireWhitelist"
      | "targetWhitelist"
      | "totalOperations"
      | "totalSponsored"
      | "transferOwnership"
      | "validatePaymasterUserOp"
      | "withdrawDeposit"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AccountRemovedFromWhitelist"
      | "AccountWhitelisted"
      | "DefaultQuotaUpdated"
      | "OwnershipTransferred"
      | "QuotaUpdated"
      | "TargetRemovedFromWhitelist"
      | "TargetWhitelisted"
      | "UserOperationSponsored"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ENTRY_POINT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "accountWhitelist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addAccountToWhitelist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addDeposit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addTargetToWhitelist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "batchAddAccountToWhitelist",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchAddTargetToWhitelist",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchSetGasQuota",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "defaultDailyQuota",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "gasQuotas",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDeposit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGasQuotaInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "getStats", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "globalDailyLimit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "globalLastResetTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "globalUsedToday",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isAccountWhitelisted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isTargetWhitelisted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "postOp",
    values: [BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAccountFromWhitelist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeTargetFromWhitelist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requireWhitelist",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultDailyQuota",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setGasQuota",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setGlobalDailyLimit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setRequireWhitelist",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "targetWhitelist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalOperations",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalSponsored",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validatePaymasterUserOp",
    values: [IEntryPoint.UserOperationStruct, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawDeposit",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "ENTRY_POINT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "accountWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addAccountToWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addDeposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addTargetToWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchAddAccountToWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchAddTargetToWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchSetGasQuota",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultDailyQuota",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gasQuotas", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getDeposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getGasQuotaInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getStats", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "globalDailyLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "globalLastResetTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "globalUsedToday",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAccountWhitelisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTargetWhitelisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "postOp", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeAccountFromWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeTargetFromWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requireWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultDailyQuota",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGasQuota",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGlobalDailyLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRequireWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "targetWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalOperations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSponsored",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validatePaymasterUserOp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawDeposit",
    data: BytesLike
  ): Result;
}

export namespace AccountRemovedFromWhitelistEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AccountWhitelistedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DefaultQuotaUpdatedEvent {
  export type InputTuple = [newQuota: BigNumberish];
  export type OutputTuple = [newQuota: bigint];
  export interface OutputObject {
    newQuota: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuotaUpdatedEvent {
  export type InputTuple = [account: AddressLike, newQuota: BigNumberish];
  export type OutputTuple = [account: string, newQuota: bigint];
  export interface OutputObject {
    account: string;
    newQuota: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TargetRemovedFromWhitelistEvent {
  export type InputTuple = [target: AddressLike];
  export type OutputTuple = [target: string];
  export interface OutputObject {
    target: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TargetWhitelistedEvent {
  export type InputTuple = [target: AddressLike];
  export type OutputTuple = [target: string];
  export interface OutputObject {
    target: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserOperationSponsoredEvent {
  export type InputTuple = [
    account: AddressLike,
    actualGasCost: BigNumberish,
    actualGasUsed: BigNumberish
  ];
  export type OutputTuple = [
    account: string,
    actualGasCost: bigint,
    actualGasUsed: bigint
  ];
  export interface OutputObject {
    account: string;
    actualGasCost: bigint;
    actualGasUsed: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DIAPPaymaster extends BaseContract {
  connect(runner?: ContractRunner | null): DIAPPaymaster;
  waitForDeployment(): Promise<this>;

  interface: DIAPPaymasterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ENTRY_POINT: TypedContractMethod<[], [string], "view">;

  accountWhitelist: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  addAccountToWhitelist: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  addDeposit: TypedContractMethod<[], [void], "payable">;

  addTargetToWhitelist: TypedContractMethod<
    [target: AddressLike],
    [void],
    "nonpayable"
  >;

  batchAddAccountToWhitelist: TypedContractMethod<
    [accounts: AddressLike[]],
    [void],
    "nonpayable"
  >;

  batchAddTargetToWhitelist: TypedContractMethod<
    [targets: AddressLike[]],
    [void],
    "nonpayable"
  >;

  batchSetGasQuota: TypedContractMethod<
    [accounts: AddressLike[], dailyQuotas: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  defaultDailyQuota: TypedContractMethod<[], [bigint], "view">;

  gasQuotas: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, boolean] & {
        dailyQuota: bigint;
        usedToday: bigint;
        lastResetTime: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getDeposit: TypedContractMethod<[], [bigint], "view">;

  getGasQuotaInfo: TypedContractMethod<
    [account: AddressLike],
    [
      [bigint, bigint, bigint, boolean] & {
        dailyQuota: bigint;
        usedToday: bigint;
        remainingToday: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        _totalSponsored: bigint;
        _totalOperations: bigint;
        _deposit: bigint;
      }
    ],
    "view"
  >;

  globalDailyLimit: TypedContractMethod<[], [bigint], "view">;

  globalLastResetTime: TypedContractMethod<[], [bigint], "view">;

  globalUsedToday: TypedContractMethod<[], [bigint], "view">;

  isAccountWhitelisted: TypedContractMethod<
    [account: AddressLike],
    [boolean],
    "view"
  >;

  isTargetWhitelisted: TypedContractMethod<
    [target: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  postOp: TypedContractMethod<
    [mode: BigNumberish, context: BytesLike, actualGasCost: BigNumberish],
    [void],
    "nonpayable"
  >;

  removeAccountFromWhitelist: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  removeTargetFromWhitelist: TypedContractMethod<
    [target: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requireWhitelist: TypedContractMethod<[], [boolean], "view">;

  setDefaultDailyQuota: TypedContractMethod<
    [quota: BigNumberish],
    [void],
    "nonpayable"
  >;

  setGasQuota: TypedContractMethod<
    [account: AddressLike, dailyQuota: BigNumberish],
    [void],
    "nonpayable"
  >;

  setGlobalDailyLimit: TypedContractMethod<
    [limit: BigNumberish],
    [void],
    "nonpayable"
  >;

  setRequireWhitelist: TypedContractMethod<
    [required: boolean],
    [void],
    "nonpayable"
  >;

  targetWhitelist: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  totalOperations: TypedContractMethod<[], [bigint], "view">;

  totalSponsored: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  validatePaymasterUserOp: TypedContractMethod<
    [
      userOp: IEntryPoint.UserOperationStruct,
      userOpHash: BytesLike,
      maxCost: BigNumberish
    ],
    [[string, bigint] & { context: string; validationData: bigint }],
    "nonpayable"
  >;

  withdrawDeposit: TypedContractMethod<
    [withdrawAddress: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ENTRY_POINT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "accountWhitelist"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "addAccountToWhitelist"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addDeposit"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "addTargetToWhitelist"
  ): TypedContractMethod<[target: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "batchAddAccountToWhitelist"
  ): TypedContractMethod<[accounts: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "batchAddTargetToWhitelist"
  ): TypedContractMethod<[targets: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "batchSetGasQuota"
  ): TypedContractMethod<
    [accounts: AddressLike[], dailyQuotas: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "defaultDailyQuota"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "gasQuotas"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, boolean] & {
        dailyQuota: bigint;
        usedToday: bigint;
        lastResetTime: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDeposit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getGasQuotaInfo"
  ): TypedContractMethod<
    [account: AddressLike],
    [
      [bigint, bigint, bigint, boolean] & {
        dailyQuota: bigint;
        usedToday: bigint;
        remainingToday: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        _totalSponsored: bigint;
        _totalOperations: bigint;
        _deposit: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "globalDailyLimit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "globalLastResetTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "globalUsedToday"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isAccountWhitelisted"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isTargetWhitelisted"
  ): TypedContractMethod<[target: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "postOp"
  ): TypedContractMethod<
    [mode: BigNumberish, context: BytesLike, actualGasCost: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeAccountFromWhitelist"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeTargetFromWhitelist"
  ): TypedContractMethod<[target: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requireWhitelist"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "setDefaultDailyQuota"
  ): TypedContractMethod<[quota: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setGasQuota"
  ): TypedContractMethod<
    [account: AddressLike, dailyQuota: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setGlobalDailyLimit"
  ): TypedContractMethod<[limit: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRequireWhitelist"
  ): TypedContractMethod<[required: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "targetWhitelist"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "totalOperations"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalSponsored"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "validatePaymasterUserOp"
  ): TypedContractMethod<
    [
      userOp: IEntryPoint.UserOperationStruct,
      userOpHash: BytesLike,
      maxCost: BigNumberish
    ],
    [[string, bigint] & { context: string; validationData: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawDeposit"
  ): TypedContractMethod<
    [withdrawAddress: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AccountRemovedFromWhitelist"
  ): TypedContractEvent<
    AccountRemovedFromWhitelistEvent.InputTuple,
    AccountRemovedFromWhitelistEvent.OutputTuple,
    AccountRemovedFromWhitelistEvent.OutputObject
  >;
  getEvent(
    key: "AccountWhitelisted"
  ): TypedContractEvent<
    AccountWhitelistedEvent.InputTuple,
    AccountWhitelistedEvent.OutputTuple,
    AccountWhitelistedEvent.OutputObject
  >;
  getEvent(
    key: "DefaultQuotaUpdated"
  ): TypedContractEvent<
    DefaultQuotaUpdatedEvent.InputTuple,
    DefaultQuotaUpdatedEvent.OutputTuple,
    DefaultQuotaUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "QuotaUpdated"
  ): TypedContractEvent<
    QuotaUpdatedEvent.InputTuple,
    QuotaUpdatedEvent.OutputTuple,
    QuotaUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TargetRemovedFromWhitelist"
  ): TypedContractEvent<
    TargetRemovedFromWhitelistEvent.InputTuple,
    TargetRemovedFromWhitelistEvent.OutputTuple,
    TargetRemovedFromWhitelistEvent.OutputObject
  >;
  getEvent(
    key: "TargetWhitelisted"
  ): TypedContractEvent<
    TargetWhitelistedEvent.InputTuple,
    TargetWhitelistedEvent.OutputTuple,
    TargetWhitelistedEvent.OutputObject
  >;
  getEvent(
    key: "UserOperationSponsored"
  ): TypedContractEvent<
    UserOperationSponsoredEvent.InputTuple,
    UserOperationSponsoredEvent.OutputTuple,
    UserOperationSponsoredEvent.OutputObject
  >;

  filters: {
    "AccountRemovedFromWhitelist(address)": TypedContractEvent<
      AccountRemovedFromWhitelistEvent.InputTuple,
      AccountRemovedFromWhitelistEvent.OutputTuple,
      AccountRemovedFromWhitelistEvent.OutputObject
    >;
    AccountRemovedFromWhitelist: TypedContractEvent<
      AccountRemovedFromWhitelistEvent.InputTuple,
      AccountRemovedFromWhitelistEvent.OutputTuple,
      AccountRemovedFromWhitelistEvent.OutputObject
    >;

    "AccountWhitelisted(address)": TypedContractEvent<
      AccountWhitelistedEvent.InputTuple,
      AccountWhitelistedEvent.OutputTuple,
      AccountWhitelistedEvent.OutputObject
    >;
    AccountWhitelisted: TypedContractEvent<
      AccountWhitelistedEvent.InputTuple,
      AccountWhitelistedEvent.OutputTuple,
      AccountWhitelistedEvent.OutputObject
    >;

    "DefaultQuotaUpdated(uint256)": TypedContractEvent<
      DefaultQuotaUpdatedEvent.InputTuple,
      DefaultQuotaUpdatedEvent.OutputTuple,
      DefaultQuotaUpdatedEvent.OutputObject
    >;
    DefaultQuotaUpdated: TypedContractEvent<
      DefaultQuotaUpdatedEvent.InputTuple,
      DefaultQuotaUpdatedEvent.OutputTuple,
      DefaultQuotaUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "QuotaUpdated(address,uint256)": TypedContractEvent<
      QuotaUpdatedEvent.InputTuple,
      QuotaUpdatedEvent.OutputTuple,
      QuotaUpdatedEvent.OutputObject
    >;
    QuotaUpdated: TypedContractEvent<
      QuotaUpdatedEvent.InputTuple,
      QuotaUpdatedEvent.OutputTuple,
      QuotaUpdatedEvent.OutputObject
    >;

    "TargetRemovedFromWhitelist(address)": TypedContractEvent<
      TargetRemovedFromWhitelistEvent.InputTuple,
      TargetRemovedFromWhitelistEvent.OutputTuple,
      TargetRemovedFromWhitelistEvent.OutputObject
    >;
    TargetRemovedFromWhitelist: TypedContractEvent<
      TargetRemovedFromWhitelistEvent.InputTuple,
      TargetRemovedFromWhitelistEvent.OutputTuple,
      TargetRemovedFromWhitelistEvent.OutputObject
    >;

    "TargetWhitelisted(address)": TypedContractEvent<
      TargetWhitelistedEvent.InputTuple,
      TargetWhitelistedEvent.OutputTuple,
      TargetWhitelistedEvent.OutputObject
    >;
    TargetWhitelisted: TypedContractEvent<
      TargetWhitelistedEvent.InputTuple,
      TargetWhitelistedEvent.OutputTuple,
      TargetWhitelistedEvent.OutputObject
    >;

    "UserOperationSponsored(address,uint256,uint256)": TypedContractEvent<
      UserOperationSponsoredEvent.InputTuple,
      UserOperationSponsoredEvent.OutputTuple,
      UserOperationSponsoredEvent.OutputObject
    >;
    UserOperationSponsored: TypedContractEvent<
      UserOperationSponsoredEvent.InputTuple,
      UserOperationSponsoredEvent.OutputTuple,
      UserOperationSponsoredEvent.OutputObject
    >;
  };
}
