/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IEntryPoint {
  export type UserOperationStruct = {
    sender: AddressLike;
    nonce: BigNumberish;
    initCode: BytesLike;
    callData: BytesLike;
    callGasLimit: BigNumberish;
    verificationGasLimit: BigNumberish;
    preVerificationGas: BigNumberish;
    maxFeePerGas: BigNumberish;
    maxPriorityFeePerGas: BigNumberish;
    paymasterAndData: BytesLike;
    signature: BytesLike;
  };

  export type UserOperationStructOutput = [
    sender: string,
    nonce: bigint,
    initCode: string,
    callData: string,
    callGasLimit: bigint,
    verificationGasLimit: bigint,
    preVerificationGas: bigint,
    maxFeePerGas: bigint,
    maxPriorityFeePerGas: bigint,
    paymasterAndData: string,
    signature: string
  ] & {
    sender: string;
    nonce: bigint;
    initCode: string;
    callData: string;
    callGasLimit: bigint;
    verificationGasLimit: bigint;
    preVerificationGas: bigint;
    maxFeePerGas: bigint;
    maxPriorityFeePerGas: bigint;
    paymasterAndData: string;
    signature: string;
  };
}

export interface DIAPAccountInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_BATCH_SIZE"
      | "addDeposit"
      | "addSessionKey"
      | "addToWhitelist"
      | "batchAddToWhitelist"
      | "batchTransferToken"
      | "defaultDailyLimit"
      | "defaultPerTxLimit"
      | "entryPoint"
      | "execute"
      | "executeBatch"
      | "executeWithSessionKey"
      | "freeze"
      | "getAllSessionKeys"
      | "getDeposit"
      | "getSessionKeyInfo"
      | "getTokenBalance"
      | "getWhitelist"
      | "initialize"
      | "isFrozen"
      | "isValidSignature"
      | "isWhitelisted"
      | "owner"
      | "removeFromWhitelist"
      | "removeSessionKey"
      | "sessionKeyList"
      | "sessionKeyNonces"
      | "sessionKeys"
      | "setDefaultDailyLimit"
      | "setDefaultPerTxLimit"
      | "transferOwnership"
      | "transferToken"
      | "unfreeze"
      | "validateUserOp"
      | "whitelist"
      | "whitelistAddresses"
      | "withdrawDepositTo"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AccountFrozenEvent"
      | "AccountUnfrozenEvent"
      | "DailyLimitUpdated"
      | "Executed"
      | "Initialized"
      | "OwnershipTransferred"
      | "PerTxLimitUpdated"
      | "SessionKeyAdded"
      | "SessionKeyRemoved"
      | "SessionKeyUsed"
      | "WhitelistAdded"
      | "WhitelistRemoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_BATCH_SIZE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addDeposit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addSessionKey",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addToWhitelist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "batchAddToWhitelist",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchTransferToken",
    values: [AddressLike, AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "defaultDailyLimit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "defaultPerTxLimit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "entryPoint",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "execute",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeBatch",
    values: [AddressLike[], BigNumberish[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "executeWithSessionKey",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "freeze", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getAllSessionKeys",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDeposit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSessionKeyInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getWhitelist",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "isFrozen", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isValidSignature",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isWhitelisted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeFromWhitelist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeSessionKey",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sessionKeyList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sessionKeyNonces",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sessionKeys",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultDailyLimit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultPerTxLimit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferToken",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "unfreeze", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "validateUserOp",
    values: [IEntryPoint.UserOperationStruct, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistAddresses",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawDepositTo",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_BATCH_SIZE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addDeposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addSessionKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addToWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchAddToWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchTransferToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultDailyLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultPerTxLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "entryPoint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeWithSessionKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "freeze", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllSessionKeys",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getDeposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSessionKeyInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isFrozen", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isValidSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isWhitelisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeFromWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeSessionKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sessionKeyList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sessionKeyNonces",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sessionKeys",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultDailyLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultPerTxLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unfreeze", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "validateUserOp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "whitelist", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "whitelistAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawDepositTo",
    data: BytesLike
  ): Result;
}

export namespace AccountFrozenEventEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AccountUnfrozenEventEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DailyLimitUpdatedEvent {
  export type InputTuple = [newLimit: BigNumberish];
  export type OutputTuple = [newLimit: bigint];
  export interface OutputObject {
    newLimit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutedEvent {
  export type InputTuple = [
    target: AddressLike,
    value: BigNumberish,
    data: BytesLike
  ];
  export type OutputTuple = [target: string, value: bigint, data: string];
  export interface OutputObject {
    target: string;
    value: bigint;
    data: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PerTxLimitUpdatedEvent {
  export type InputTuple = [newLimit: BigNumberish];
  export type OutputTuple = [newLimit: bigint];
  export interface OutputObject {
    newLimit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SessionKeyAddedEvent {
  export type InputTuple = [
    key: AddressLike,
    validUntil: BigNumberish,
    dailyLimit: BigNumberish
  ];
  export type OutputTuple = [
    key: string,
    validUntil: bigint,
    dailyLimit: bigint
  ];
  export interface OutputObject {
    key: string;
    validUntil: bigint;
    dailyLimit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SessionKeyRemovedEvent {
  export type InputTuple = [key: AddressLike];
  export type OutputTuple = [key: string];
  export interface OutputObject {
    key: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SessionKeyUsedEvent {
  export type InputTuple = [key: AddressLike, amount: BigNumberish];
  export type OutputTuple = [key: string, amount: bigint];
  export interface OutputObject {
    key: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WhitelistAddedEvent {
  export type InputTuple = [target: AddressLike];
  export type OutputTuple = [target: string];
  export interface OutputObject {
    target: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WhitelistRemovedEvent {
  export type InputTuple = [target: AddressLike];
  export type OutputTuple = [target: string];
  export interface OutputObject {
    target: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DIAPAccount extends BaseContract {
  connect(runner?: ContractRunner | null): DIAPAccount;
  waitForDeployment(): Promise<this>;

  interface: DIAPAccountInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_BATCH_SIZE: TypedContractMethod<[], [bigint], "view">;

  addDeposit: TypedContractMethod<[], [void], "payable">;

  addSessionKey: TypedContractMethod<
    [
      key: AddressLike,
      validUntil: BigNumberish,
      dailyLimit: BigNumberish,
      perTxLimit: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  addToWhitelist: TypedContractMethod<
    [target: AddressLike],
    [void],
    "nonpayable"
  >;

  batchAddToWhitelist: TypedContractMethod<
    [targets: AddressLike[]],
    [void],
    "nonpayable"
  >;

  batchTransferToken: TypedContractMethod<
    [token: AddressLike, recipients: AddressLike[], amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  defaultDailyLimit: TypedContractMethod<[], [bigint], "view">;

  defaultPerTxLimit: TypedContractMethod<[], [bigint], "view">;

  entryPoint: TypedContractMethod<[], [string], "view">;

  execute: TypedContractMethod<
    [dest: AddressLike, value: BigNumberish, func: BytesLike],
    [void],
    "nonpayable"
  >;

  executeBatch: TypedContractMethod<
    [dest: AddressLike[], value: BigNumberish[], func: BytesLike[]],
    [void],
    "nonpayable"
  >;

  executeWithSessionKey: TypedContractMethod<
    [dest: AddressLike, value: BigNumberish, func: BytesLike],
    [void],
    "nonpayable"
  >;

  freeze: TypedContractMethod<[], [void], "nonpayable">;

  getAllSessionKeys: TypedContractMethod<[], [string[]], "view">;

  getDeposit: TypedContractMethod<[], [bigint], "view">;

  getSessionKeyInfo: TypedContractMethod<
    [key: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean] & {
        validUntil: bigint;
        dailyLimit: bigint;
        perTxLimit: bigint;
        spentToday: bigint;
        remainingToday: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getTokenBalance: TypedContractMethod<[token: AddressLike], [bigint], "view">;

  getWhitelist: TypedContractMethod<[], [string[]], "view">;

  initialize: TypedContractMethod<[anOwner: AddressLike], [void], "nonpayable">;

  isFrozen: TypedContractMethod<[], [boolean], "view">;

  isValidSignature: TypedContractMethod<
    [hash: BytesLike, signature: BytesLike],
    [string],
    "view"
  >;

  isWhitelisted: TypedContractMethod<[target: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  removeFromWhitelist: TypedContractMethod<
    [target: AddressLike],
    [void],
    "nonpayable"
  >;

  removeSessionKey: TypedContractMethod<
    [key: AddressLike],
    [void],
    "nonpayable"
  >;

  sessionKeyList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  sessionKeyNonces: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  sessionKeys: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean] & {
        validUntil: bigint;
        dailyLimit: bigint;
        perTxLimit: bigint;
        spentToday: bigint;
        lastResetTime: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  setDefaultDailyLimit: TypedContractMethod<
    [limit: BigNumberish],
    [void],
    "nonpayable"
  >;

  setDefaultPerTxLimit: TypedContractMethod<
    [limit: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  transferToken: TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  unfreeze: TypedContractMethod<[], [void], "nonpayable">;

  validateUserOp: TypedContractMethod<
    [
      userOp: IEntryPoint.UserOperationStruct,
      userOpHash: BytesLike,
      missingAccountFunds: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  whitelist: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  whitelistAddresses: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  withdrawDepositTo: TypedContractMethod<
    [withdrawAddress: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_BATCH_SIZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addDeposit"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "addSessionKey"
  ): TypedContractMethod<
    [
      key: AddressLike,
      validUntil: BigNumberish,
      dailyLimit: BigNumberish,
      perTxLimit: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addToWhitelist"
  ): TypedContractMethod<[target: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "batchAddToWhitelist"
  ): TypedContractMethod<[targets: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "batchTransferToken"
  ): TypedContractMethod<
    [token: AddressLike, recipients: AddressLike[], amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "defaultDailyLimit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "defaultPerTxLimit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "entryPoint"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "execute"
  ): TypedContractMethod<
    [dest: AddressLike, value: BigNumberish, func: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeBatch"
  ): TypedContractMethod<
    [dest: AddressLike[], value: BigNumberish[], func: BytesLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeWithSessionKey"
  ): TypedContractMethod<
    [dest: AddressLike, value: BigNumberish, func: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "freeze"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAllSessionKeys"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getDeposit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSessionKeyInfo"
  ): TypedContractMethod<
    [key: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean] & {
        validUntil: bigint;
        dailyLimit: bigint;
        perTxLimit: bigint;
        spentToday: bigint;
        remainingToday: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTokenBalance"
  ): TypedContractMethod<[token: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getWhitelist"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<[anOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isFrozen"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isValidSignature"
  ): TypedContractMethod<
    [hash: BytesLike, signature: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "isWhitelisted"
  ): TypedContractMethod<[target: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeFromWhitelist"
  ): TypedContractMethod<[target: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeSessionKey"
  ): TypedContractMethod<[key: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sessionKeyList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "sessionKeyNonces"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "sessionKeys"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean] & {
        validUntil: bigint;
        dailyLimit: bigint;
        perTxLimit: bigint;
        spentToday: bigint;
        lastResetTime: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setDefaultDailyLimit"
  ): TypedContractMethod<[limit: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDefaultPerTxLimit"
  ): TypedContractMethod<[limit: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferToken"
  ): TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unfreeze"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "validateUserOp"
  ): TypedContractMethod<
    [
      userOp: IEntryPoint.UserOperationStruct,
      userOpHash: BytesLike,
      missingAccountFunds: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "whitelist"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "whitelistAddresses"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "withdrawDepositTo"
  ): TypedContractMethod<
    [withdrawAddress: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AccountFrozenEvent"
  ): TypedContractEvent<
    AccountFrozenEventEvent.InputTuple,
    AccountFrozenEventEvent.OutputTuple,
    AccountFrozenEventEvent.OutputObject
  >;
  getEvent(
    key: "AccountUnfrozenEvent"
  ): TypedContractEvent<
    AccountUnfrozenEventEvent.InputTuple,
    AccountUnfrozenEventEvent.OutputTuple,
    AccountUnfrozenEventEvent.OutputObject
  >;
  getEvent(
    key: "DailyLimitUpdated"
  ): TypedContractEvent<
    DailyLimitUpdatedEvent.InputTuple,
    DailyLimitUpdatedEvent.OutputTuple,
    DailyLimitUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Executed"
  ): TypedContractEvent<
    ExecutedEvent.InputTuple,
    ExecutedEvent.OutputTuple,
    ExecutedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PerTxLimitUpdated"
  ): TypedContractEvent<
    PerTxLimitUpdatedEvent.InputTuple,
    PerTxLimitUpdatedEvent.OutputTuple,
    PerTxLimitUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SessionKeyAdded"
  ): TypedContractEvent<
    SessionKeyAddedEvent.InputTuple,
    SessionKeyAddedEvent.OutputTuple,
    SessionKeyAddedEvent.OutputObject
  >;
  getEvent(
    key: "SessionKeyRemoved"
  ): TypedContractEvent<
    SessionKeyRemovedEvent.InputTuple,
    SessionKeyRemovedEvent.OutputTuple,
    SessionKeyRemovedEvent.OutputObject
  >;
  getEvent(
    key: "SessionKeyUsed"
  ): TypedContractEvent<
    SessionKeyUsedEvent.InputTuple,
    SessionKeyUsedEvent.OutputTuple,
    SessionKeyUsedEvent.OutputObject
  >;
  getEvent(
    key: "WhitelistAdded"
  ): TypedContractEvent<
    WhitelistAddedEvent.InputTuple,
    WhitelistAddedEvent.OutputTuple,
    WhitelistAddedEvent.OutputObject
  >;
  getEvent(
    key: "WhitelistRemoved"
  ): TypedContractEvent<
    WhitelistRemovedEvent.InputTuple,
    WhitelistRemovedEvent.OutputTuple,
    WhitelistRemovedEvent.OutputObject
  >;

  filters: {
    "AccountFrozenEvent()": TypedContractEvent<
      AccountFrozenEventEvent.InputTuple,
      AccountFrozenEventEvent.OutputTuple,
      AccountFrozenEventEvent.OutputObject
    >;
    AccountFrozenEvent: TypedContractEvent<
      AccountFrozenEventEvent.InputTuple,
      AccountFrozenEventEvent.OutputTuple,
      AccountFrozenEventEvent.OutputObject
    >;

    "AccountUnfrozenEvent()": TypedContractEvent<
      AccountUnfrozenEventEvent.InputTuple,
      AccountUnfrozenEventEvent.OutputTuple,
      AccountUnfrozenEventEvent.OutputObject
    >;
    AccountUnfrozenEvent: TypedContractEvent<
      AccountUnfrozenEventEvent.InputTuple,
      AccountUnfrozenEventEvent.OutputTuple,
      AccountUnfrozenEventEvent.OutputObject
    >;

    "DailyLimitUpdated(uint256)": TypedContractEvent<
      DailyLimitUpdatedEvent.InputTuple,
      DailyLimitUpdatedEvent.OutputTuple,
      DailyLimitUpdatedEvent.OutputObject
    >;
    DailyLimitUpdated: TypedContractEvent<
      DailyLimitUpdatedEvent.InputTuple,
      DailyLimitUpdatedEvent.OutputTuple,
      DailyLimitUpdatedEvent.OutputObject
    >;

    "Executed(address,uint256,bytes)": TypedContractEvent<
      ExecutedEvent.InputTuple,
      ExecutedEvent.OutputTuple,
      ExecutedEvent.OutputObject
    >;
    Executed: TypedContractEvent<
      ExecutedEvent.InputTuple,
      ExecutedEvent.OutputTuple,
      ExecutedEvent.OutputObject
    >;

    "Initialized(uint8)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PerTxLimitUpdated(uint256)": TypedContractEvent<
      PerTxLimitUpdatedEvent.InputTuple,
      PerTxLimitUpdatedEvent.OutputTuple,
      PerTxLimitUpdatedEvent.OutputObject
    >;
    PerTxLimitUpdated: TypedContractEvent<
      PerTxLimitUpdatedEvent.InputTuple,
      PerTxLimitUpdatedEvent.OutputTuple,
      PerTxLimitUpdatedEvent.OutputObject
    >;

    "SessionKeyAdded(address,uint256,uint256)": TypedContractEvent<
      SessionKeyAddedEvent.InputTuple,
      SessionKeyAddedEvent.OutputTuple,
      SessionKeyAddedEvent.OutputObject
    >;
    SessionKeyAdded: TypedContractEvent<
      SessionKeyAddedEvent.InputTuple,
      SessionKeyAddedEvent.OutputTuple,
      SessionKeyAddedEvent.OutputObject
    >;

    "SessionKeyRemoved(address)": TypedContractEvent<
      SessionKeyRemovedEvent.InputTuple,
      SessionKeyRemovedEvent.OutputTuple,
      SessionKeyRemovedEvent.OutputObject
    >;
    SessionKeyRemoved: TypedContractEvent<
      SessionKeyRemovedEvent.InputTuple,
      SessionKeyRemovedEvent.OutputTuple,
      SessionKeyRemovedEvent.OutputObject
    >;

    "SessionKeyUsed(address,uint256)": TypedContractEvent<
      SessionKeyUsedEvent.InputTuple,
      SessionKeyUsedEvent.OutputTuple,
      SessionKeyUsedEvent.OutputObject
    >;
    SessionKeyUsed: TypedContractEvent<
      SessionKeyUsedEvent.InputTuple,
      SessionKeyUsedEvent.OutputTuple,
      SessionKeyUsedEvent.OutputObject
    >;

    "WhitelistAdded(address)": TypedContractEvent<
      WhitelistAddedEvent.InputTuple,
      WhitelistAddedEvent.OutputTuple,
      WhitelistAddedEvent.OutputObject
    >;
    WhitelistAdded: TypedContractEvent<
      WhitelistAddedEvent.InputTuple,
      WhitelistAddedEvent.OutputTuple,
      WhitelistAddedEvent.OutputObject
    >;

    "WhitelistRemoved(address)": TypedContractEvent<
      WhitelistRemovedEvent.InputTuple,
      WhitelistRemovedEvent.OutputTuple,
      WhitelistRemovedEvent.OutputObject
    >;
    WhitelistRemoved: TypedContractEvent<
      WhitelistRemovedEvent.InputTuple,
      WhitelistRemovedEvent.OutputTuple,
      WhitelistRemovedEvent.OutputObject
    >;
  };
}
